# Generated by Django 2.2.28 on 2025-03-05 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['user'], 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AddField(
            model_name='thread',
            name='topic',
            field=models.CharField(default='', max_length=20000),
            preserve_default=False,
        ),
    ]
