# Generated by Django 2.2.28 on 2025-03-11 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20250311_1211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-written_on'], 'verbose_name_plural': 'Posts'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_on',
            new_name='written_on',
        ),
    ]
