# Generated by Django 2.2.28 on 2025-03-11 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20250311_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='created_on',
            new_name='started_on',
        ),
    ]
