# Generated by Django 2.2.28 on 2025-03-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20250311_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='last_visit',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='created_on',
        ),
        migrations.AddField(
            model_name='article',
            name='edited_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='edited_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='edited_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
