# Generated by Django 2.2.28 on 2025-03-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20250311_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='updated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
