# Generated by Django 2.2.28 on 2025-03-11 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20250311_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='edited_on',
            new_name='updated_on',
        ),
    ]
