# Generated by Django 2.2.28 on 2025-03-22 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20250322_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_picture',
            new_name='article_image',
        ),
    ]
